repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v2.3.0'
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: "docker/Dockerfile, .devcontainer.json"
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v15.0.7'
    hooks:
    -   id: clang-format
        args: [-i, --style=file]
        exclude: '.devcontainer.json'
