name: Compile Examples

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  unittests-linux-generic:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/modm-ext/modm-build-avr:latest

    strategy:
      fail-fast: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -f docker/Dockerfile -t avr-ubuntu .

      - name: Run unit tests
        run: docker run --rm avr-ubuntu /workspaces/swing/build_and_run_unittest.sh

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results
